Wait 300 milliseconds before tearDown to give the FlickerTLW's wx.CallLater a chance to run, which avoids this exception:
wx/core.py, line 3096, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
RuntimeError: wrapped C/C++ object of type Filling has been deleted

Ensure that the Crust object's "lastsashpos" attribute is defined to avoid this exception:

wx/py/crust.py", line 150, in SaveSettings
    if self.lastsashpos != -1:
AttributeError: 'Crust' object has no attribute 'lastsashpos'