Skipping this test, because when the ToasterBox instance (tb) goes out of scope, the following exception is raised:
RuntimeError: super-class __init__() of type ToasterBox was never called